apiVersion: v1
kind: Pod
metadata:
  labels:
    app: result
  name: result-pod
spec:
  containers:
  - image: dockersamples/examplevotingapp_result
    name: result
    ports:
    - containerPort: 80
      name: result
