apiVersion: v1
kind: Pod
metadata:
  labels:
    app: vote
  name: vote-pod
spec:
  containers:
  - image: dockersamples/examplevotingapp_vote
    name: vote
    ports:
    - containerPort: 80
      name: vote
